<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2015/09/16 08:03:27
sfConfig::add(array(
  'mod_recruitmentapply_enabled' => true,
  'mod_recruitmentapply_view_class' => 'sfPHP',
));
